import json
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from langchain_core.tools import tool
from services.logger_setup import get_core_logger

logger = get_core_logger(__name__)

class DatasetItem(BaseModel):
    label: str
    data: List[float]
    backgroundColor: Optional[List[str]] = None

class GenerateUIChartInput(BaseModel):
    chart_type: str = Field(..., description="'bar', 'line', 'pie', 'radar', or 'doughnut'")
    title: str = Field(..., description="Title of the chart")
    labels: List[str] = Field(..., description="X-axis labels (e.g. ['Food', 'Transport'])")
    datasets: List[DatasetItem] = Field(..., description="The actual data to chart")

@tool(args_schema=GenerateUIChartInput)
def generate_ui_chart(chart_type: str, title: str, labels: List[str], datasets: List[Dict[str, Any]]) -> str:
    """
    Renders a dynamic chart directly in the user's chat interface.
    Pass the aggregated data exactly as you want it visualized.
    """
    logger.info(json.dumps({"message": f"Executing MCP Tool: generate_ui_chart ({chart_type})", "status_code": 200}))
    
    # We don't actually do anything on the backend. 
    # We just return a success message because the stream_chat interceptor 
    # will catch this tool call and forward the payload to the frontend!
    return "UI Chart successfully rendered in the chat."

class SpawnWidgetInput(BaseModel):
    widget_type: str = Field(..., description="MUST BE EXACTLY ONE OF: 'Cashflow', 'Categories', 'ConnectedAccounts', 'Transactions', 'Trends', 'Health', 'Subscriptions', 'Anomalies', 'Risk', 'Habits'")

@tool(args_schema=SpawnWidgetInput)
def spawn_dashboard_widget(widget_type: str, user_uuid: str = None) -> str:
    """
    Spawns a new widget on the user's persistent dashboard.
    ONLY use this if the user explicitly asks to add something to their dashboard or track something over time.
    """
    from config import SessionLocal
    from models.database_models import User
    
    logger.info(json.dumps({"message": f"Executing MCP Tool: spawn_dashboard_widget ({widget_type})", "status_code": 200}))
    
    valid_types = ['Cashflow', 'Categories', 'ConnectedAccounts', 'Transactions', 'Trends', 'Health', 'Subscriptions', 'Anomalies', 'Risk', 'Habits']
    if widget_type not in valid_types:
        return f"Error: widget_type must be one of {valid_types}"
        
    try:
        with SessionLocal() as session:
            user = session.query(User).filter(User.user_uuid == user_uuid).first()
            if not user:
                return "Error: User not found."
            
            # Since dashboard layouts are dynamically generated by persona and manual 
            # widgets are saved in the frontend's LocalStorage, we do not save the 
            # widget payload to the database anymore.
            
            return f"Successfully added {widget_type} widget to the dashboard (Note: AI widgets are currently tied to the Persona profile, so tell the user to manually add this using the frontend 'Add Widget' button if they want it permanently!)."
    except Exception as e:
        logger.error(json.dumps({"message": f"Error spawning widget: {e}", "status_code": 500}))
        return f"Error spawning widget: {str(e)}"
